-- Example — Bitbucket Cloud (default):
--   require("atlas").setup({
--     pulls = {
--       providers = {
--         bitbucket = {
--           user  = vim.env.BITBUCKET_USER,
--           token = vim.env.BITBUCKET_TOKEN,
--           cache_ttl = 300,
--           views = {
--             {
--               name = "All",
--               key  = "1",
--               repos = {
--                 { workspace = "acme", repo = "core" },
--                 { workspace = "acme", repo = "web" },
--               },
--             },
--             {
--               name = "Reviewing",
--               key  = "2",
--               layout = "compact",
--               repos = { { workspace = "acme", repo = "core" } },
--               filter = function(pr, ctx)
--                 if ctx.user == nil then return true end
--                 for _, r in ipairs(pr._raw and pr._raw.reviewers or {}) do
--                   if r.uuid == ctx.user.id then return true end
--                 end
--                 return false
--               end,
--             },
--           },
--         },
--       },
--     },
--   })
--
-- Example — Bitbucket Server / Data Center:
--   bitbucket = {
--     api_type = "server",
--     base_url = "https://bitbucket.your-company.com",
--     user     = "admin",
--     token    = vim.env.BITBUCKET_TOKEN,         -- PAT or password
--     views = {
--       {
--         name = "All",
--         key  = "1",
--         repos = {
--           -- `workspace` doubles as the project key on Server.
--           { workspace = "ACME", repo = "core" },
--         },
--       },
--     },
--   }

---@class AtlasBitbucketRepoRef
---@field workspace string  on Cloud: workspace slug; on Server: project key
---@field repo string

---@class AtlasBitbucketViewConfig : AtlasPullsViewConfig
---@field repos AtlasBitbucketRepoRef[]|nil
---@field filter? fun(pr: PullRequest, ctx: { user: PullsUser|nil }): boolean|nil
---@field status? "OPEN"|"MERGED"|"DECLINED"|"SUPERSEDED"

---@class AtlasBitbucketConfig
---@field user string
---@field token string
---@field api_type "cloud"|"server"|nil  defaults to "cloud"
---@field base_url string|nil            required when api_type = "server"
---@field cache_ttl number|nil
---@field views AtlasBitbucketViewConfig[]|nil
